# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  runc: go run ./cmd/consumer/main.go
  runp: go run ./cmd/producer/main.go